import { useMemo, useState, type FormEvent } from "react";
import { Link, Route, Routes, useLocation } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type SessionUser } from "./api.js";

type Habit = { id: string; name: string; icon: string; hue: string; streak: number; done: boolean; detail: string; goal?: string };
const nav = [{ to: "/", icon: "◷", label: "Today" }, { to: "/dashboard", icon: "▦", label: "Overview" }, { to: "/history", icon: "▧", label: "History" }, { to: "/goals", icon: "◎", label: "Goals" }, { to: "/achievements", icon: "✳", label: "Awards" }];

function todayLabel() { return new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(new Date()); }
function localDate() { const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); return `${parts.find(p=>p.type==="year")?.value}-${parts.find(p=>p.type==="month")?.value}-${parts.find(p=>p.type==="day")?.value}`; }
function useHabits() {
  const queryClient = useQueryClient();
  const date = localDate();
  const categoriesQuery = useQuery({ queryKey: ["categories"], queryFn: () => api<{categories:Array<{_id:string;name:string;icon:string;accent?:string;archivedAt?:string|null;schedule:{kind:string}}> }>("/categories") });
  const entriesQuery = useQuery({ queryKey: ["entries", date], queryFn: () => api<{entries:Array<{_id:string;categoryId:string;localDate:string;status:string;note:string}>}>(`/entries?from=${date}&to=${date}`) });
  const statsQuery = useQuery({ queryKey: ["stats", date], queryFn: () => api<{categories:Array<{category:{id:string};currentStreak:number}>}>(`/stats?from=${date}&to=${date}`) });
  const save = useMutation({ mutationFn: (body:{categoryId:string;localDate:string;status:"completed"|"missed"|"skipped";note?:string}) => api("/entries", { method:"PUT", body:JSON.stringify(body) }), onSuccess:()=>queryClient.invalidateQueries() });
  const createCategory = useMutation({ mutationFn:(name:string)=>api("/categories",{method:"POST",body:JSON.stringify({name,icon:"✦",schedule:{kind:"daily"}})}),onSuccess:()=>queryClient.invalidateQueries({queryKey:["categories"]}) });
  const entries = entriesQuery.data?.entries ?? [];
  const categoryList = categoriesQuery.data?.categories.filter(c=>!c.archivedAt) ?? [];
  const habits: Habit[] = categoryList.map(category=>{
    const entry = entries.find(item=>item.categoryId===category._id);
    const streak = statsQuery.data?.categories.find(item=>item.category.id===category._id)?.currentStreak ?? 0;
    return { id:category._id,name:category.name,icon:category.icon,hue:["lilac","mint","peach","blue"][categoryList.indexOf(category)%4]!,streak,done:entry?.status==="completed",detail:entry?.note ?? "Add a note about today's progress" };
  });
  const update = (next: Habit[]) => {
    for (const habit of next) {
      const old = habits.find(item=>item.id===habit.id);
      if (!old || old.done!==habit.done || old.detail!==habit.detail) void save.mutateAsync({categoryId:habit.id,localDate:date,status:habit.done?"completed":"missed",note:habit.detail.startsWith("Add a note")?"":habit.detail});
    }
  };
  return { habits, update, create:(name:string)=>createCategory.mutate(name), isLoading:categoriesQuery.isLoading||entriesQuery.isLoading, error:categoriesQuery.error??entriesQuery.error };
}
function Shell({ children }: { children: React.ReactNode }) {
  const location = useLocation();
  return <div className="app-frame">
    <aside className="sidebar"><Link to="/" className="wordmark"><span className="logo-glyph">s</span><span>steady<span className="wordmark-dot">.</span></span></Link>
      <div className="side-caption">YOUR SPACE</div><nav className="side-nav" aria-label="Main navigation">{nav.map((item) => <Link key={item.to} to={item.to} className={`nav-link ${location.pathname === item.to ? "active" : ""}`}><span className="nav-icon">{item.icon}</span>{item.label}{item.to === "/" && <span className="nav-live" />}</Link>)}</nav>
      <div className="sidebar-bottom"><div className="quote-mark">“</div><p>Small steps, repeated, become a way forward.</p><span>YOUR DAILY REMINDER</span></div>
      <Link to="/settings" className={`settings-link ${location.pathname === "/settings" ? "active" : ""}`}><span className="nav-icon">⚙</span>Settings</Link>
    </aside>
    <main className="main-area"><header className="mobile-header"><Link to="/" className="wordmark"><span className="logo-glyph">s</span><span>steady<span className="wordmark-dot">.</span></span></Link><span className="avatar">S</span></header>{children}</main>
    <nav className="mobile-nav" aria-label="Mobile navigation">{nav.slice(0, 5).map(item => <Link key={item.to} to={item.to} className={location.pathname === item.to ? "active" : ""}><span>{item.icon}</span><small>{item.label}</small></Link>)}</nav>
  </div>;
}

function Today() {
  const { habits, update, create, isLoading, error } = useHabits();
  const [openNote, setOpenNote] = useState<string | null>(null);
  const [journal, setJournal] = useState(() => localStorage.getItem("steady-journal") ?? "");
  const complete = habits.filter(h => h.done).length;
  const percent = habits.length ? Math.round(100 * complete / habits.length) : 0;
  const toggle = (id: string) => update(habits.map(h => h.id === id ? { ...h, done: !h.done } : h));
  const [draftNotes, setDraftNotes] = useState<Record<string,string>>({});
  const noteChange = (id: string, detail: string) => setDraftNotes(notes=>({...notes,[id]:detail}));
  return <div className="content-wrap today-view">
    <div className="page-top"><div><div className="date-label"><span className="date-dot" />{todayLabel()}</div><h1>Today, <em>gently.</em></h1><p className="page-intro">A few small promises to yourself. Start anywhere.</p></div><button className="icon-button profile-button" aria-label="Profile">S</button></div>
    <section className="daily-overview" aria-label="Today's progress"><div className="overview-copy"><span className="section-kicker">YOUR DAILY RHYTHM</span><h2>{complete === habits.length && habits.length ? "You showed up for yourself." : complete ? "A good start is already a start." : "Make room for what matters."}</h2><p>{complete === habits.length && habits.length ? "Today is yours. Take a moment to feel good about that." : `${habits.length - complete} ${habits.length - complete === 1 ? "practice" : "practices"} left whenever you're ready.`}</p></div><div className="progress-ring" style={{ "--progress": `${percent * 3.6}deg` } as React.CSSProperties}><div><strong>{complete}<span>/{habits.length}</span></strong><small>DONE</small></div></div><div className="overview-footer"><span>{complete === habits.length && habits.length ? "✦ Perfectly present today" : `${percent}% of today's intentions`}</span><span>{complete} completed</span></div></section>
    <div className="section-heading"><div><span className="section-kicker">YOUR PRACTICES</span><h2>What matters today</h2></div><button className="text-action" onClick={() => { const name=window.prompt("Name your new daily practice"); if(name?.trim()) create(name.trim()); }}>＋ Add a practice</button></div>
    {isLoading?<div className="panel muted">Loading your practices…</div>:error?<div className="panel error-panel">Could not load your practices. Check that the API and MongoDB are running, then refresh.</div>:<section className="habit-list" aria-label="Daily practices">{habits.map((habit, i) => <article className={`habit-card ${habit.done ? "is-done" : ""}`} key={habit.id} style={{ animationDelay: `${i * 55}ms` }}>
      <button className={`habit-check ${habit.done ? "checked" : ""}`} onClick={() => toggle(habit.id)} aria-label={`${habit.done ? "Mark incomplete" : "Mark complete"}: ${habit.name}`} aria-pressed={habit.done}>{habit.done && <span>✓</span>}</button>
      <div className={`habit-symbol ${habit.hue}`}>{habit.icon}</div><div className="habit-main"><div className="habit-title-row"><h3>{habit.name}</h3>{habit.goal && <span className="goal-tag"><span>◎</span>{habit.goal}</span>}</div><p>{habit.detail || "Add a note about today's progress"}</p></div>
      <div className="habit-streak"><span className="flame">♨</span><strong>{habit.streak}</strong><small>DAY STREAK</small></div><button className="note-button" onClick={() => setOpenNote(openNote === habit.id ? null : habit.id)}>{habit.detail.startsWith("Add a note") ? "Add note" : "Details"}<span>↗</span></button>
      {openNote === habit.id && <div className="note-editor"><label htmlFor={`note-${habit.id}`}>A note for today</label><textarea id={`note-${habit.id}`} value={draftNotes[habit.id] ?? (habit.detail.startsWith("Add a note") ? "" : habit.detail)} onChange={e => noteChange(habit.id, e.target.value)} placeholder="What did you work on?" rows={2} autoFocus /><button onClick={() => { if (draftNotes[habit.id] !== undefined) update(habits.map(h=>h.id===habit.id?{...h,detail:draftNotes[habit.id]||"Add a note about today's progress"}:h)); setOpenNote(null); }}>Done</button></div>}
    </article>)}</section>}
    <section className="journal-card"><div className="journal-icon">✎</div><div className="journal-content"><div className="journal-heading"><div><span className="section-kicker">A LITTLE REFLECTION</span><h3>Today's note</h3></div><span className="optional-pill">OPTIONAL</span></div><textarea aria-label="Today's journal note" placeholder="Anything you want to remember about today?" value={journal} onChange={e => { setJournal(e.target.value); localStorage.setItem("steady-journal", e.target.value); }} rows={2} /></div></section>
    <footer className="today-footer"><span>Consistency is returning, again and again.</span><span>Saved on this device</span></footer>
  </div>;
}

function Overview() {
  const { habits } = useHabits();
  const to=localDate();const fromDate=new Date(`${to}T00:00:00`);fromDate.setDate(fromDate.getDate()-6);const from=new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit"}).format(fromDate);
  const weekQuery=useQuery({queryKey:["week-stats",from,to],queryFn:()=>api<{daily:Array<{date:string;scheduled:number;completed:number;percent:number}>;totals:{scheduled:number;completed:number}}>(`/stats?from=${from}&to=${to}`)});
  const done = habits.filter(h => h.done).length;
  const week=weekQuery.data?.daily??[];
  return <div className="content-wrap"><div className="page-top"><div><div className="date-label"><span className="date-dot" />YOUR PROGRESS</div><h1>Steady <em>looks good.</em></h1><p className="page-intro">A wider view of the work you're putting in.</p></div></div><div className="stats-grid"><Stat label="Today completed" value={`${done} / ${habits.length}`} icon="◷"/><Stat label="Active practices" value={`${habits.length}`} icon="✳"/><Stat label="Current best streak" value={`${Math.max(...habits.map(h=>h.streak),0)} days`} icon="♨"/></div><section className="panel"><div className="section-heading"><div><span className="section-kicker">THIS WEEK</span><h2>Showing up adds up</h2></div><span className="muted">{weekQuery.data?.totals.completed??0} / {weekQuery.data?.totals.scheduled??0} practices</span></div><div className="week-bars">{week.map(day=><div className="week-day" key={day.date} title={`${day.completed}/${day.scheduled} completed`}><div className="week-track"><span style={{height:`${day.scheduled?Math.max(8,day.percent):4}%`}}/></div><small>{new Intl.DateTimeFormat(undefined,{weekday:"narrow"}).format(new Date(`${day.date}T12:00:00`))}</small></div>)}</div><p className="chart-caption">Your rhythm is made from ordinary days like these.</p></section><section className="panel streak-panel"><div className="section-heading"><div><span className="section-kicker">PRACTICES</span><h2>Keep your rhythm</h2></div><Link className="text-action" to="/history">See history ↗</Link></div>{habits.map(h=><div className="streak-row" key={h.id}><div className={`mini-symbol ${h.hue}`}>{h.icon}</div><strong>{h.name}</strong><span className="streak-number">♨ {h.streak}</span><div className="mini-progress"><span style={{width:`${Math.min(100,h.streak*4)}%`}}/></div></div>)}</section></div>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:string}) { return <div className="stat-card"><span className="stat-icon">{icon}</span><span className="stat-label">{label}</span><strong>{value}</strong><small>Keep your pace, your way</small></div>; }

function History() {
  const [filter, setFilter] = useState("All practices");
  const { habits } = useHabits();
  const historyQuery=useQuery({queryKey:["history-stats",filter],queryFn:()=>{const category=habits.find(h=>h.name===filter);const path=filter==="All practices"||!category?"/stats":`/stats?categoryId=${encodeURIComponent(category.id)}`;return api<{daily:Array<{date:string;scheduled:number;completed:number;percent:number}>;categories:Array<{category:{name:string};currentStreak:number;longestStreak:number;completionRate:number}>;totals:{scheduled:number;completed:number}}>(path);}});
  const days=historyQuery.data?.daily??[];
  const rate=historyQuery.data?.totals.scheduled?Math.round(historyQuery.data.totals.completed/historyQuery.data.totals.scheduled*100):0;
  const current=Math.max(0,...(historyQuery.data?.categories.map(item=>item.currentStreak)??[]));
  return <div className="content-wrap"><div className="page-top"><div><div className="date-label"><span className="date-dot" />YOUR CONSISTENCY</div><h1>Look how far <em>you've come.</em></h1><p className="page-intro">Every mark is a day you made an effort.</p></div></div><section className="panel heatmap-panel"><div className="section-heading"><div><span className="section-kicker">YOUR ACTIVITY</span><h2>Small steps, over time</h2></div><select aria-label="Filter activity" value={filter} onChange={e=>setFilter(e.target.value)}><option>All practices</option>{habits.map(h=><option key={h.id}>{h.name}</option>)}</select></div>{historyQuery.isLoading?<p className="muted">Loading your history…</p>:<><div className="heatmap-months"><span>{days[0]?.date.slice(5,7)??""}</span><span>90 DAYS</span><span>{days.at(-1)?.date.slice(5,7)??""}</span></div><div className="heatmap-wrap"><div className="heatmap-weekdays"><span>M</span><span>W</span><span>F</span></div><div className="heatmap">{days.map(day=>{const level=day.percent===0?0:day.percent<40?1:day.percent<80?2:3;return <button key={day.date} className={`heat-cell level-${level}`} title={`${day.date}: ${day.completed}/${day.scheduled} completed`} aria-label={`${day.date}: ${day.completed} of ${day.scheduled} scheduled practices completed`} />})}</div></div><div className="heatmap-legend"><span>Less</span>{[0,1,2,3].map(i=><i key={i} className={`heat-cell level-${i}`}/>)}<span>More</span></div></>}</section><div className="stats-grid history-stats"><Stat label="Current streak" value={`${current} days`} icon="♨"/><Stat label="Completed check-ins" value={`${historyQuery.data?.totals.completed??0}`} icon="✦"/><Stat label="Schedule completion" value={`${rate}%`} icon="↗"/></div><section className="panel"><span className="section-kicker">A NOTE TO YOURSELF</span><h2 className="quote-title">“You don't have to see the whole staircase, just take the first step.”</h2><p className="muted">Your history is calculated from your recorded practices.</p></section></div>;
}

type GoalListResponse = { goals: Array<{ goal: { _id:string; title:string; categoryId:string; startDate:string; targetDate:string; metrics:Array<{_id:string;label:string;unit:string;target:number}> }; metrics:Array<{target:number;value:number}>; progress:number; pace:{status:string;daysLeft:number;expectedPercent:number;requiredPerDay:Array<{remaining:number;perDay:number}>} }> };
function Goals() {
  const queryClient=useQueryClient();
  const goalsQuery=useQuery({queryKey:["goals"],queryFn:()=>api<GoalListResponse>("/goals")});
  const categoriesQuery=useQuery({queryKey:["categories"],queryFn:()=>api<{categories:Array<{_id:string;name:string;archivedAt?:string|null}>}>("/categories")});
  const refresh=()=>queryClient.invalidateQueries({queryKey:["goals"]});
  async function createGoal(){const categories=categoriesQuery.data?.categories.filter(c=>!c.archivedAt)??[];if(!categories.length){window.alert("Add a practice category first.");return;}const title=window.prompt("What do you want to finish?");if(!title?.trim())return;const metricText=window.prompt("What will you count? Enter components like Chapters:12, Videos:30");if(!metricText)return;const metrics=metricText.split(",").map((part,index)=>{const [label,total]=part.split(":");return{key:`metric-${index+1}`,label:label?.trim()??"",unit:label?.trim()??"units",target:Number(total)}});if(metrics.some(m=>!m.label||!Number.isFinite(m.target)||m.target<=0)){window.alert("Use a label and positive target, such as Chapters:12.");return;}const category=categories[0]!;const startDate=localDate();const targetDate=window.prompt("Target date (YYYY-MM-DD)",startDate);if(!targetDate)return;try{await api("/goals",{method:"POST",body:JSON.stringify({categoryId:category._id,title,startDate,targetDate,metrics})});refresh();}catch(e){window.alert(e instanceof Error?e.message:"Could not create goal.");}}
  async function addProgress(goalId:string,metricId:string,label:string){const amount=Number(window.prompt(`How many ${label.toLowerCase()} did you complete?`,"1"));if(!Number.isFinite(amount)||amount<=0)return;try{await api(`/goals/${goalId}/progress`,{method:"POST",body:JSON.stringify({localDate:localDate(),changes:[{metricId,amount}]})});refresh();}catch(e){window.alert(e instanceof Error?e.message:"Could not update goal.");}}
  const goals=goalsQuery.data?.goals??[];
  return <div className="content-wrap"><div className="page-top"><div><div className="date-label"><span className="date-dot" />THE BIGGER PICTURE</div><h1>Progress with <em>purpose.</em></h1><p className="page-intro">Meaningful goals, broken into doable pieces.</p></div><button className="primary-button" onClick={()=>void createGoal()}>＋ New goal</button></div>{goalsQuery.isLoading?<div className="panel muted">Loading goals…</div>:goals.length?<div className="goal-list">{goals.map(({goal,metrics,progress,pace})=><article className="goal-card" key={goal._id}><div className="goal-top"><div><span className="goal-category">{categoriesQuery.data?.categories.find(c=>c._id===goal.categoryId)?.name??"Category"}</span><h2>{goal.title}</h2></div><span className="pace-tag">↗ {pace.status.replaceAll("-"," ")}</span></div><div className="goal-progress-row"><div className="goal-progress"><span style={{width:`${progress}%`,background:"#7ba78a"}}/></div><strong>{Math.round(progress)}%</strong></div><div className="goal-subrow"><span>{pace.daysLeft} days left</span><span>Expected {Math.round(pace.expectedPercent)}%</span></div><div className="metric-list">{goal.metrics.map((metric,index)=><div className="metric-row" key={metric._id}><span>{metric.label}</span><div className="metric-track"><i style={{width:`${Math.min(100,metrics[index]!.value/metric.target*100)}%`}}/></div><span>{metrics[index]?.value??0} / {metric.target}</span><button className="metric-add" aria-label={`Add progress to ${metric.label}`} onClick={()=>void addProgress(goal._id,metric._id,metric.label)}>＋</button></div>)}</div></article>)}</div>:<div className="panel empty-panel"><h2>No goals yet</h2><p>Choose one finite outcome and track the pieces that get you there.</p></div>}<p className="muted goal-footnote">Progress should feel like a guide, never a verdict.</p></div>;
}

function Awards() { const query=useQuery({queryKey:["achievements"],queryFn:()=>api<{achievements:Array<{key:string;title:string;description:string;icon:string;unlockedAt:string|null}>}>("/achievements")});const awards=query.data?.achievements??[];return <div className="content-wrap"><div className="page-top"><div><div className="date-label"><span className="date-dot" />MILESTONES, BIG AND SMALL</div><h1>Things worth <em>celebrating.</em></h1><p className="page-intro">Not trophies. Reminders of what you can do.</p></div></div>{query.isLoading?<div className="panel muted">Checking your milestones…</div>:<div className="award-grid">{awards.map(a=><article className={`award-card ${a.unlockedAt?"unlocked":"locked"}`} key={a.key}><div className="award-medal">{a.icon}</div><div><h3>{a.title}</h3><p>{a.description}</p></div><span className="award-state">{a.unlockedAt?`UNLOCKED · ${new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(a.unlockedAt))}`:"IN YOUR FUTURE"}</span></article>)}</div>}</div>}

type CategoryList={categories:Array<{_id:string;name:string;icon:string;archivedAt:string|null;schedule:{kind:string}}>};
function CategoryManager(){const queryClient=useQueryClient();const query=useQuery({queryKey:["categories"],queryFn:()=>api<CategoryList>("/categories")});async function act(id:string,method:string,path=""){await api(`/categories/${id}${path}`,{method});await queryClient.invalidateQueries({queryKey:["categories"]});}async function rename(item:{_id:string;name:string}){const name=window.prompt("Rename this practice",item.name);if(name?.trim()&&name!==item.name){await api(`/categories/${item._id}`,{method:"PATCH",body:JSON.stringify({name})});await queryClient.invalidateQueries({queryKey:["categories"]});}}return <section className="panel category-settings"><div className="section-heading"><div><span className="section-kicker">YOUR PRACTICES</span><h2>Manage categories</h2></div></div>{query.data?.categories.map(category=><div className="setting-row" key={category._id}><div className="category-setting-name"><span>{category.icon}</span><div><h3>{category.name}{category.archivedAt&&<small className="archived-label"> · Archived</small>}</h3><p>{category.schedule.kind.replaceAll("-"," ")}</p></div></div><div>{category.archivedAt?<button className="text-action" onClick={()=>void act(category._id,"POST","/restore")}>Restore</button>:<><button className="text-action" onClick={()=>void rename(category)}>Rename</button><button className="text-action archive-action" onClick={()=>void act(category._id,"DELETE")}>Archive</button></>}</div></div>)}</section>}
function Settings() { const download=async(format:"json"|"csv")=>{try{const response=await fetch(`/api/export?format=${format}`,{credentials:"include"});if(!response.ok)throw new Error("Export failed");const blob=await response.blob();const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=format==="json"?"steady-backup.json":"steady-entries.csv";link.click();URL.revokeObjectURL(link.href);}catch{window.alert("Could not export data. Check your connection.");}};return <div className="content-wrap"><div className="page-top"><div><div className="date-label"><span className="date-dot" />MAKE IT YOURS</div><h1>Your space, <em>your way.</em></h1><p className="page-intro">A few settings to make Steady fit your life.</p></div></div><section className="panel settings-panel"><div className="setting-row"><div><h3>Appearance</h3><p>Choose a calm light or dark workspace.</p></div><select aria-label="Appearance"><option>Light</option><option>Dark</option><option>System</option></select></div><div className="setting-row"><div><h3>Time zone</h3><p>Your days and streaks follow local time.</p></div><span>{Intl.DateTimeFormat().resolvedOptions().timeZone}</span></div><div className="setting-row"><div><h3>Data backup</h3><p>Download your data. CSV exports daily entries.</p></div><div><button className="text-action" onClick={()=>void download("json")}>JSON ↗</button><button className="text-action" onClick={()=>void download("csv")}>CSV ↗</button></div></div><div className="setting-row"><div><h3>Account</h3><p>Sign out of this account on this device.</p></div><button className="primary-button" onClick={async()=>{await api("/auth/logout",{method:"POST"});window.location.reload();}}>Sign out</button></div></section><CategoryManager/></div> }

function AuthGate({children}:{children:React.ReactNode}) {
  const queryClient=useQueryClient();
  const session=useQuery({queryKey:["session"],queryFn:()=>api<{user:SessionUser}>("/auth/me"),retry:false,refetchOnWindowFocus:false});
  const [register,setRegister]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);const form=new FormData(event.currentTarget);const payload={email:String(form.get("email")),password:String(form.get("password")),...(register?{displayName:String(form.get("name")),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}:{})};try{const result=await api<{user:SessionUser}>(register?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(payload)});queryClient.setQueryData(["session"],result);await queryClient.invalidateQueries();}catch(e){setError(e instanceof Error?e.message:"Unable to sign in.");}finally{setBusy(false);}}
  if(session.isLoading)return <div className="auth-loading">Getting your space ready…</div>;
  if(session.data?.user)return <>{children}</>;
  return <main className="auth-page"><div className="auth-card"><Link to="/" className="wordmark"><span className="logo-glyph">s</span><span>steady<span className="wordmark-dot">.</span></span></Link><div className="date-label"><span className="date-dot"/>{register?"A FRESH START":"WELCOME BACK"}</div><h1>{register?<>Make space for <em>progress.</em></>:<>Come back to <em>yourself.</em></>}</h1><p className="page-intro">{register?"Create an account to keep your practices and progress in sync.":"Sign in to pick up right where you left off."}</p><form className="auth-form" onSubmit={submit}>{register&&<label>Your name<input name="name" required maxLength={80} autoComplete="name"/></label>}<label>Email address<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={10} maxLength={72} autoComplete={register?"new-password":"current-password"}/><small>At least 10 characters</small></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={busy}>{busy?"Please wait…":register?"Create account":"Sign in"}</button></form><button className="text-action auth-switch" onClick={()=>{setRegister(!register);setError("");}}>{register?"Already have an account? Sign in":"New to Steady? Create an account"}</button></div><span className="auth-footnote">Small steps, repeated, become a way forward.</span></main>;
}
function NotFound() { return <div className="content-wrap"><h1>One day at a time.</h1><Link className="text-action" to="/">Back to Today →</Link></div>; }
export default function App() { return <AuthGate><Shell><Routes><Route path="/" element={<Today/>}/><Route path="/dashboard" element={<Overview/>}/><Route path="/history" element={<History/>}/><Route path="/goals" element={<Goals/>}/><Route path="/achievements" element={<Awards/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<NotFound/>}/></Routes></Shell></AuthGate>; }
